name: Deploy

on:
  push:
    branches:
      - develop
      - master

env:
  SWARMLET_USER: git
  SWARMLET_HOST: swarmlet.dev
  SWARMLET_APP_NAME: swarmlet-website

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set environment
        run: |
          echo "BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
          echo "SWARMLET_APP_NAME=$SWARMLET_APP_NAME-staging" >> $GITHUB_ENV

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v1
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          known-hosts: ${{ env.SWARMLET_HOST }}

      - name: Deploy to swarm
        run: |
          cd $GITHUB_WORKSPACE
          git fetch --unshallow
          git remote add swarm $SWARMLET_USER@$SWARMLET_HOST:$SWARMLET_APP_NAME
          GIT_SSH_COMMAND="ssh -i $HOME/.ssh/id_rsa -F /dev/null -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" \
          git push -u swarm $BRANCH:master --force

      - name: Slack notify
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "${{ env.SWARMLET_APP_NAME }} deployed:"
          SLACK_USERNAME: Swarmbot
          SLACK_ICON_EMOJI: ":swarmlet:"
