name: Deploy to swarm

env:
  GITHUB_SHA: ${{ github.sha }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SWARMLET_USER: git
  SWARMLET_HOST: swarmlet.dev
  SWARMLET_APP_NAME: swarmlet-website
  SWARMLET_REMOTE_BRANCH: master

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      run: |
        # Setup the SSH environment
        mkdir -p ~/.ssh
        eval `ssh-agent -s`
        ssh-add - <<< $SSH_PRIVATE_KEY
        ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
        ssh-keyscan $SWARMLET_HOST >> ~/.ssh/known_hosts
        chown 400 ~/.ssh/id_rsa

        # Setup the git environment
        REMOTE_URL=$SWARMLET_USER@$SWARMLET_HOST:$SWARMLET_APP_NAME
        cd $GITHUB_WORKSPACE
        git remote add swarm $REMOTE_URL

        # Prepare to push to swarm git repository
        REMOTE_REF=$GITHUB_SHA:refs/heads/$SWARMLET_REMOTE_BRANCH:master
        GIT_COMMAND="git push swarm $REMOTE_REF"
        echo "GIT_COMMAND=$GIT_COMMAND"

        # Push to swarm git repository
        GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa -F /dev/null -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" $GIT_COMMAND

        
