name: Deploy

on:
  push:
    branches:
      - develop
      - master

env:
  SWARMLET_USER: git
  SWARMLET_HOST: swarmlet.dev
  SWARMLET_APP_NAME: swarmlet-website

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set environment
      run: echo "::set-env name=BRANCH::$(echo ${GITHUB_REF##*/})"

    - name: Set app name [staging]
      if: env.BRANCH == 'develop'
      run: echo "::set-env name=SWARMLET_APP_NAME::$SWARMLET_APP_NAME-staging"
    
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v1
      with:
        private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        known-hosts: ${{ env.SWARMLET_HOST }}

    - name: Deploy to swarm
      run: |
        cd $GITHUB_WORKSPACE
        git checkout $BRANCH
        git fetch --unshallow
        git remote add swarm $SWARMLET_USER@$SWARMLET_HOST:$SWARMLET_APP_NAME
        GIT_SSH_COMMAND="ssh -i $HOME/.ssh/id_rsa -F /dev/null -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" \
        git push -u swarm $BRANCH:master
